FROM node:20-slim
WORKDIR /frontend

COPY package.json package-lock.json ./

# RUN npm install
RUN rm -rf node_modules package-lock.json && npm install

RUN npm install -g rollup

COPY . .

EXPOSE 5173

RUN npm run build

CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]