services:
  backend:
    build: ./backend
    container_name: flask-backend
    restart: always
    ports:
      - "5000:5000"
    networks:
      - app-network
    env_file:
      - ./backend/.env
    environment:
      # Auth0 backend verification vars (fallback if not in .env file)
      AUTH0_DOMAIN: ${AUTH0_DOMAIN:-}
      AUTH0_AUDIENCE: ${AUTH0_AUDIENCE:-}
      AUTH0_API_ISSUER: ${AUTH0_API_ISSUER:-}
      AUTH0_ALGORITHMS: ${AUTH0_ALGORITHMS:-RS256}

  frontend:
    build: ./frontend
    container_name: react-frontend
    restart: always
    ports:
      - "5173:5173"
    depends_on:
      - backend
    volumes:
      - ./frontend:/frontend
      - node_modules:/frontend/node_modules
    networks:
      - app-network
    env_file:
      - ./frontend/.env
    environment:
      # Tell Vite proxy what host to target inside the Docker network.
      VITE_BACKEND_HOST: flask-backend
      VITE_BACKEND_PORT: 5000
      # Auth0 SPA configuration (provide real values or use an .env file in /frontend)
      VITE_AUTH0_DOMAIN: ${VITE_AUTH0_DOMAIN:-}
      VITE_AUTH0_CLIENT_ID: ${VITE_AUTH0_CLIENT_ID:-}
      VITE_AUTH0_AUDIENCE: ${VITE_AUTH0_AUDIENCE:-}
      # Improve file change detection on some host OS setups
      CHOKIDAR_USEPOLLING: "true"

networks:
  app-network:
    driver: bridge

volumes:
  node_modules: