services:
  backend:
    build: ./backend
    container_name: flask-backend
    restart: always
    ports:
      - "5000:5000"
    networks:
      - app-network
    env_file:
      - ./backend/.env

  frontend:
    build: ./frontend
    container_name: react-frontend
    restart: always
    ports:
      - "5173:5173"
    depends_on:
      - backend
    volumes:
      - ./frontend:/frontend
      - node_modules:/frontend/node_modules
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  node_modules: